/**
 * Keeps public/sitemap.xml in sync with dynamic content (published blog
 * posts, countries, active urgent requirements) stored in Supabase.
 *
 * The site is a static build uploaded to Hostinger — there is no serverless
 * function to generate a sitemap on request, so this runs at build time,
 * before `vite build`, and rewrites public/sitemap.xml in place. Existing
 * hand-curated <url> entries (homepage, hub pages, guides) are preserved
 * exactly; only entries for dynamic content are added, updated, or removed
 * to match what is actually live in the database right now.
 *
 * Requires VITE_SUPABASE_URL + VITE_SUPABASE_ANON_KEY (same values used by
 * the client app) to be available as env vars or in .env. If they are not
 * set, this script logs a warning and leaves sitemap.xml untouched rather
 * than failing the build.
 */
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadEnv } from 'vite'
import { createClient } from '@supabase/supabase-js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const sitemapPath = path.join(root, 'public', 'sitemap.xml')
const SITE_URL = 'https://siddhivinayakoverseas.com'

const env = { ...loadEnv('production', root, ''), ...process.env }
const SUPABASE_URL = env.VITE_SUPABASE_URL
const SUPABASE_ANON_KEY = env.VITE_SUPABASE_ANON_KEY || env.VITE_SUPABASE_PUBLISHABLE_KEY

const DYNAMIC_MARKER_START = '<!-- BEGIN dynamic (generated by scripts/generate-sitemap.mjs — do not hand-edit this block) -->'
const DYNAMIC_MARKER_END = '<!-- END dynamic -->'

function urlEntry({ loc, lastmod, changefreq, priority }) {
  return [
    '  <url>',
    `    <loc>${loc}</loc>`,
    lastmod ? `    <lastmod>${lastmod}</lastmod>` : null,
    changefreq ? `    <changefreq>${changefreq}</changefreq>` : null,
    priority ? `    <priority>${priority}</priority>` : null,
    '  </url>',
  ]
    .filter(Boolean)
    .join('\n')
}

function isoDate(value) {
  if (!value) return new Date().toISOString().slice(0, 10)
  return new Date(value).toISOString().slice(0, 10)
}

async function fetchDynamicEntries(supabase) {
  const entries = []

  const { data: posts, error: postsError } = await supabase
    .from('blog_posts')
    .select('slug, updated_at, published_at')
    .eq('status', 'published')
  if (postsError) {
    console.warn(`[sitemap] blog_posts query failed: ${postsError.message}`)
  } else {
    for (const post of posts ?? []) {
      if (!post.slug) continue
      entries.push(
        urlEntry({
          loc: `${SITE_URL}/blog/${post.slug}`,
          lastmod: isoDate(post.updated_at || post.published_at),
          changefreq: 'monthly',
          priority: '0.70',
        }),
      )
    }
  }

  const { data: countries, error: countriesError } = await supabase
    .from('countries')
    .select('slug, updated_at')
  if (countriesError) {
    console.warn(`[sitemap] countries query failed: ${countriesError.message}`)
  } else {
    for (const country of countries ?? []) {
      if (!country.slug) continue
      entries.push(
        urlEntry({
          loc: `${SITE_URL}/countries/${country.slug}`,
          lastmod: isoDate(country.updated_at),
          changefreq: 'weekly',
          priority: '0.80',
        }),
      )
    }
  }

  const { data: urgent, error: urgentError } = await supabase
    .from('urgent_requirements')
    .select('slug, updated_at, status')
    .eq('status', 'active')
  if (urgentError) {
    console.warn(`[sitemap] urgent_requirements query failed: ${urgentError.message}`)
  } else {
    for (const item of urgent ?? []) {
      if (!item.slug) continue
      entries.push(
        urlEntry({
          loc: `${SITE_URL}/urgent-requirements/${item.slug}`,
          lastmod: isoDate(item.updated_at),
          changefreq: 'daily',
          priority: '0.75',
        }),
      )
    }
  }

  return entries
}

async function main() {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.warn(
      '[sitemap] VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY not set — skipping dynamic sitemap update, keeping public/sitemap.xml as-is.',
    )
    return
  }

  const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
  const dynamicEntries = await fetchDynamicEntries(supabase)

  const existing = await readFile(sitemapPath, 'utf8')
  const dynamicBlock = `${DYNAMIC_MARKER_START}\n${dynamicEntries.join('\n')}\n${DYNAMIC_MARKER_END}`

  let next
  if (existing.includes(DYNAMIC_MARKER_START) && existing.includes(DYNAMIC_MARKER_END)) {
    const startIdx = existing.indexOf(DYNAMIC_MARKER_START)
    const endIdx = existing.indexOf(DYNAMIC_MARKER_END) + DYNAMIC_MARKER_END.length
    next = existing.slice(0, startIdx) + dynamicBlock + existing.slice(endIdx)
  } else {
    next = existing.replace('</urlset>', `${dynamicBlock}\n</urlset>`)
  }

  await writeFile(sitemapPath, next, 'utf8')
  console.log(`[sitemap] Synced ${dynamicEntries.length} dynamic URL(s) into public/sitemap.xml`)
}

main().catch((err) => {
  console.error('[sitemap] Failed to update sitemap:', err)
  // Non-fatal — never block a production build over a sitemap sync failure.
})
